# Generated by Django 3.2.6 on 2022-05-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0010_rename_category_id_catalogsmodel_category'),
        ('home', '0002_entitiesmodel_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.IntegerField()),
                ('broadcast_date', models.DateField(auto_now=True)),
                ('currency', models.IntegerField()),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('series', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogsmodel')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.entitiesmodel')),
            ],
        ),
    ]
