# Generated by Django 3.2.6 on 2022-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesmodel',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
