# Generated by Django 3.2.6 on 2022-04-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
                ('type', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('primary_email', models.CharField(max_length=200)),
                ('first_email', models.CharField(max_length=200, null=True)),
                ('second_email', models.CharField(max_length=200, null=True)),
                ('mobile_number', models.CharField(max_length=200, null=True)),
                ('fijo', models.CharField(max_length=200, null=True)),
                ('client_detraccion', models.CharField(max_length=200, null=True)),
                ('detail', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
