# Generated by Django 3.2.6 on 2022-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitiesmodel',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
