# Generated by Django 3.2.6 on 2022-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
