# Generated by Django 3.2.6 on 2022-04-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_categoriesmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='category_code',
            field=models.CharField(max_length=30),
        ),
    ]
