# Generated by Django 3.2.6 on 2022-04-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalogsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsmodel',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
