# Generated by Django 3.2.6 on 2022-04-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_catalogsmodel_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogsmodel',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
    ]
