# Generated by Django 3.2.6 on 2022-04-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_catalogsmodel_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogsmodel',
            name='category_id',
        ),
    ]
