# Generated by Django 3.2.6 on 2022-04-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_catalogsmodel_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsmodel',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.categoriesmodel'),
            preserve_default=False,
        ),
    ]
